# Generated by Django 5.0.6 on 2024-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='academia.user'),
        ),
    ]
