# Generated by Django 5.0.6 on 2024-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_alter_curso_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
