# Generated by Django 5.0.6 on 2024-07-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
    ]
