import type { Metadata } from 'next';
import './globals.css';

import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';
import { Header } from '@/components/pages/global/Header';
import { ThemeProvider } from '@/components/providers/ThemeProvider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={
        cn(
          'min-h-screen bg-background/100 font-sans antialiased w-full',
          fontSans.variable,
        )
      }
      >
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
